# Generated by Django 4.2.5 on 2024-11-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
